export const FETCH_ALL_STARTED='FETCH_ALL_STARTED';
export const FETCH_ALL_SUCCCESS='FETCH_ALL_SUCCESS';
export const FETCH_ALL_FAILED='FETCH_ALL_FAILED';


export const FETCH_BY_NAME_STARTED='FETCH_BY_NAME_STARTED';
export const FETCH_BY_NAME_FAILED='FETCH_BY_NAME_FAILED';
export const FETCH_BY_NAME_SUCCESS='FETCH_BY_NAME_SUCCESS';

export const FETCH_BY_CUISINE_STARTED='FETCH_BY_CUISINE_STARTED';
export const FETCH_BY_CUISINE_FAILED='FETCH_BY_CUISINE_FAILED';
export const FETCH_BY_CUISINE_SUCCESS='FETCH_BY_CUISINE_SUCCESS';

export const FETCH_BY_ID_STARTED='FETCH_BY_ID_STARTED';
export const FETCH_BY_ID_FAILED='FETCH_BY_ID_FAILED';
export const FETCH_BY_ID_SUCCESS='FETCH_BY_ID_SUCCESS';